### ISSUE TITLE
Does not work on Wayland

### ISSUE THREAD

**Issue by ocludo** [nailfarmer/gnome-shell-dim-on-battery-extension#11]
This was working on Xorg, but is not working on Wayland. Fedora 27, GNOME 3.26. It works if power is connected/disconnected, but the correct state is not selected when the system starts (first login). Haven't tested the latest version with Xorg, though.

**Comment by nailfarmer** [comment]
Hi @ocludo, there's a fix for this now in master, seems the dbus brightness interface sometimes takes a short while after wayland login to settle down so that properties are properly exposed.  I've added a workaround for this.  Can you please test if you get a chance, and reopen if this doesn't solve the issue for you?  Many thanks!

**Comment by ocludo** [comment]
@nailfarmer: Seems to be working fine now, barring a few quirks of Wayland (such as a split-second delay in reducing the brightness, but it doesn't bother me). Thanks for fixing it.

**Comment by nailfarmer** [comment]
Yeah, sadly there's not much I can do about the delay.  Glad that it doesn't keep you from using the extension!
